In [1]:
import numpy as np
import matplotlib.pyplot as plt
import itertools
import math
from pyparsing import python_style_comment
from itertools import islice
import scipy.sparse as sps
from scipy.sparse import diags
from functools import lru_cache
import pandas as pd

# Working on Mutual Information Starting from Conditional Probability

## Flip Bit for M = 1 

In [2]:
# Conditional probability matrix [P(Y|X)]
p = 0.1
q = 0.9

# Consider the Flip Bit case for M = 1 
P_Y_X = np.array([[q, p],
                  [p, q]])

M = np.shape(P_Y_X)[0] / 2

# Marginal probabilities P(X) and P(Y)
# prob_x = np.array([1/4, 1/4])
# prob_y = np.array([1/4, 1/4])

# PX = np.sum(prob_x, axis = 0).sum()
# PY = np.sum(prob_y, axis = 0).sum()
PX = 0.5
PY = 0.5

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = PX * P_Y_X
P_X_Y = P_XY / PY

# Entropy
# HX = np.sum(-(prob_x) * np.log2(prob_x))
HX = - np.log2(PX)
HY = - np.log2(PY)

H_XY = - np.log2(P_XY)
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [3]:
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):')
print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Number of Time Bin 1.0
Probability P(X): 0.5
Probability P(Y): 0.5
Joint Probability P(X,Y):
[[0.45 0.05]
 [0.05 0.45]]
Conditional Probability P(X|Y):
[[0.9 0.1]
 [0.1 0.9]]
Conditional Probability P(Y|X):
[[0.9 0.1]
 [0.1 0.9]]
Entropy H(X): 1.0
Entropy H(Y): 1.0
Joint Entropy H(X,Y):
[[1.15200309 4.32192809]
 [4.32192809 1.15200309]]
Conditional Entropy H(X|Y): 0.4689955933007422
Conditional Entropy H(Y|X): 0.4689955933007422
Mutual Information I(X;Y)): 0.5310044066992579
Mutual Information per Photon I(X;Y)/(M/2)): 1.0620088133985157


## Flip Bit for M = 2

In [4]:
p = 0.1
q = 0.9

# Conditional probability matrix [P(Y|X)]
# Consider the flip bit case for M = 2 
P_Y_X = np.array([[q*q, q*p, p*q, p*p],
                  [q*p, q*q, p*p, p*q],
                  [p*q, p*p, q*q, q*p],
                  [p*p, p*q, q*p, q*q]])

M = np.shape(P_Y_X)[0] / 2

# Marginal probabilities P(X) and P(Y)
# prob_x = np.array([1/4, 0])
# prob_y = np.array([1/8, 1/8])

# PX = np.sum(prob_x, axis = 0).sum()
# PY = np.sum(prob_y, axis = 0).sum()
PX = 1/4
PY = 1/4

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = PX * P_Y_X 
P_X_Y = P_XY / PY

# Entropy
HX = - np.log2(PX)
HY = - np.log2(PY)

H_XY = - np.log2(P_XY)
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [5]:
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):')
print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Number of Time Bin 2.0
Probability P(X): 0.25
Probability P(Y): 0.25
Joint Probability P(X,Y):
[[0.2025 0.0225 0.0225 0.0025]
 [0.0225 0.2025 0.0025 0.0225]
 [0.0225 0.0025 0.2025 0.0225]
 [0.0025 0.0225 0.0225 0.2025]]
Conditional Probability P(X|Y):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Conditional Probability P(Y|X):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Entropy H(X): 2.0
Entropy H(Y): 2.0
Joint Entropy H(X,Y):
[[2.30400619 5.47393119 5.47393119 8.64385619]
 [5.47393119 2.30400619 8.64385619 5.47393119]
 [5.47393119 8.64385619 2.30400619 5.47393119]
 [8.64385619 5.47393119 5.47393119 2.30400619]]
Conditional Entropy H(X|Y): 0.9379911866014845
Conditional Entropy H(Y|X): 0.9379911866014845
Mutual Information I(X;Y)): 1.0620088133985155
Mutual Information per Photon I(X;Y)/(M/2)): 1.0620088133985155


# Creating a square matrix based on $2^m$ Possibilities in m time bins

Generate nxn square matrix based the 2^n possibilities. 

For example, 

n = 1, I should have 2x2 square matrix, 

n = 2, I should have 4x4 square matrix, 

n = 3, I should have 8x8 square matrix and so on.

Also,the elements correspond to specific combination of bits.

The values (m=1,o=0,p=0.1,q=0.9) represent the values associated with each bit combination. 

Using the mapping, I can determine the corresponding value for each element in the square matrix based on the binary representation of its row and columnb indices.

For example, for n = 1, we have 2^1 possibilities. Based the following code, we have the possbilities


In [25]:
def generate_bit_combinations(n):
    combinations = []
    for i in range(2**n):
        binary = bin(i)[2:].zfill(n)  # Convert the decimal number to binary
        combinations.append(binary)
    return combinations

In [26]:
generate_bit_combinations(1)

['0', '1']

Let us read from digit to digit.


For the matrix element 11, the binary representation is from '0' to '0', so we should assign the value of m to this element.


For the matrix element 12, the binary representation is from '0' to '1', so we should assign the value of o to this element.


For the matrix element 21, the binary representation is from '1' to '0', so we should assign the value of p to this element.


For the matrix element 22, the binary representation is from '1' to '1', so we should assign the value of q to this element.

Therefore, we should have the following as the square matrix:

[[1, 0], 

[0.1, 0.9]]


For n = 2, we have 2^2 possibilities. Based the following code, we have the possbilities

['00', '01', '10', '11']

Let us read from digit to digit.

For the matrix element 11, the binary representation is from 0 to 0 for the first digit and from 0 to 0 for the second digit, so we should assign the value of m * m  = 1 * 1 = 1 to this element.

For the matrix element 12, the binary representation is from 0 to 0 for the first digit and from 0 to 1 for the second digit, so we should assign the value of m * o = 1 * 0 = 0 to this element.

For the matrix element 13, the binary representation is from 0 to 1 for the first digit and from 0 to 0 for the second digit, so we should assign the value of o * m = 0 * 1 = 0 to this element.

For the matrix element 14, the binary representation is from 0 to 1 for the first digit and from 0 to 1 for the second digit, so we should assign the value of o * o = 0 * 0 = 0 to this element.

For the matrix element 21, the binary representation is from 0 to 0 for the first digit and from 1 to 0 for the second digit, so we should assign the value of m * p = 1 * 0.1 = 0.1 to this element.

For the matrix element 22, the binary representation is from 0 to 0 for the first digit and from 1 to 1 for the second digit, so we should assign the value of m * q = 1 * 0.9 = 0.9 to this element.

For the matrix element 23, the binary representation is from 0 to 1 for the first digit and from 1 to 0 for the second digit, so we should assign the value of o * p = 0 * 0.1 = 0 to this element.

For the matrix element 24, the binary representation is from 0 to 1 for the first digit and from 1 to 1 for the second digit, so we should assign the value of o * q = 0 * 0.9 = 0 to this element.

For the matrix element 31, the binary representation is from 1 to 0 for the first digit and from 0 to 0 for the second digit, so we should assign the value of p * m = 0.1 * 1 = 0.1 to this element.

For the matrix element 32, the binary representation is from 1 to 0 for the first digit and from 0 to 1 for the second digit, so we should assign the value of p * o = 0.1 * 0 = 0 to this element.

For the matrix element 33, the binary representation is from 1 to 1 for the first digit and from 0 to 0 for the second digit, so we should assign the value of q * m = 0.9 * 1 = 0.9 to this element.

For the matrix element 34, the binary representation is from 1 to 1 for the first digit and from 0 to 1 for the second digit, so we should assign the value of q * o = 0.9 * 0 = 0 to this element.

For the matrix element 41, the binary representation is from 1 to 0 for the first digit and from 1 to 0 for the second digit, so we should assign the value of p * p = 0.1 * 0.1 = 0.01 to this element.

For the matrix element 42, the binary representation is from 1 to 0 for the first digit and from 1 to 1 for the second digit, so we should assign the value of p * q = 0.1 * 0.9 = 0.09 to this element.

For the matrix element 43, the binary representation is from 1 to 1 for the first digit and from 1 to 0 for the second digit, so we should assign the value of q * p = 0.9 * 0.1 = 0.09 to this element.

For the matrix element 44, the binary representation is from 1 to 1 for the first digit and from 1 to 1 for the second digit, so we should assign the value of q * q = 0.9 * 0.9 = 0.81 to this element.

Therefore, we should have the following as the square matrix:

[[m * m, m * o, o * m, o * o], 

[m * p, m * q, o * p, o * q], 

[p * m, p * o, q * m, q * o], 

[p * p, p * q, q * p, q * q]]

=

[[1, 0, 0, 0], 

[0.1, 0.9, 0, 0],

 [0.1, 0, 0.9, 0], 
 
 [0.01, 0.09, 0.09, 0.81]]


The generated square matrix has dimensions 4x4, and each element corresponds to the calculated value based on the binary representation of its row and column indices.

In [6]:
import numpy as np

In [7]:
def M(n_OOK):
    return 2*n_OOK 

def K(M):
    return 2**M

def matrix_size(n_OOK):
    return 2**n_OOK

def P_XY(matrix_size):
    # matrix_size as the parameter represents the size of the square matrix
    # initialize the size by np.zeros
    matrix = np.zeros((matrix_size, matrix_size))
    
    # nested for loops iterate over the indices i and j ranging from 0 to matrix_size - 1

    for i in range(matrix_size):
        for j in range(matrix_size):
            # obtaining the binary represnentation of row and colum indices
            # bin converts the decimal index to a binary string
            # [2:] removes the "0b" prefix from the binary string"
            # zfill(n_OOK) ensures the binrary string is zero-padded to the length n_OOK

            row_binary = bin(i)[2:].zfill(n_OOK)  # Binary representation of row index
            col_binary = bin(j)[2:].zfill(n_OOK)  # Binary representation of column index

            # m is initialized to be 1.0
            # for loop iterates over the rnage n_OOK, corresponding to the length of the binary representation


#             The innermost for loop iterates over the range n_OOK, which corresponds to the length of the binary representation.

# Inside the loop, conditional statements check the values of the binary digits (row_binary[k] and col_binary[k]) at the same position (k).

# If row_binary[k] is '0' and col_binary[k] is '1', it means the current bit combination is '01'. In this case, the value of m is updated by multiplying it with o.

# If row_binary[k] is '1' and col_binary[k] is '0', it means the current bit combination is '10'. The value of m is updated by multiplying it with p.

# If row_binary[k] and col_binary[k] are both '1', it means the current bit combination is '11'. The value of m is updated by multiplying it with q.

# After updating m based on the bit combinations, the value of m is assigned to the corresponding element in the matrix using matrix[i][j] = m.

# Finally, the function returns the generated matrix as a NumPy array using np.array(matrix).

# In summary, the code generates a square matrix of size matrix_size and assigns values to each element based on the binary representation of its row and column indices. The values 'm', 'o', 'p', and 'q' are multiplied according to the bit combinations, and the resulting matrix is returned.
           
            m = 1.0  # Default value for 'm'
            for k in range(n_OOK):
                if row_binary[k] == '0' and col_binary[k] == '1':
                    m *= o  # Update value to 'o'
                elif row_binary[k] == '1' and col_binary[k] == '0':
                    m *= p  # Update value to 'p'
                elif row_binary[k] == '1' and col_binary[k] == '1':
                    m *= q  # Update value to 'q'

            matrix[i][j] = m
    
    return np.array(matrix) 

def P_XY_OOK(P_XY, K):
    return P_XY * (1/K)

def P_X(P_XY_OOK):
    PX = np.sum(P_XY_OOK, axis=1)
    return PX

def P_Y(P_XY_OOK):
    PY = np.sum(P_XY_OOK, axis=0)
    return PY

def P_Y_X(P_XY_OOK, PX): 
    PYX = P_XY_OOK / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
    return PYX

def P_X_Y(P_XY_OOK, PY): 
    PXY = P_XY_OOK / PY
    return PXY

def H_X(P_X):
    HX = -np.sum(P_X * np.log2(P_X))
    return HX

def H_Y(P_Y):
    HY = -np.sum(P_Y * np.log2(P_Y))
    return HY

def H_XY(P_XY_OOK):
    HXY = -np.sum(P_XY_OOK * np.log2(P_XY_OOK + 1e-10))
    return HXY

def H_X_Y(P_XY_OOK, P_X_Y):
    HXY = -np.sum(P_XY_OOK * np.log2(P_X_Y + 1e-10), axis=0).sum()
    return HXY

def H_Y_X(P_XY_OOK, P_Y_X): 
    HYX = -np.sum(P_XY_OOK * np.log2(P_Y_X + 1e-10), axis=0).sum()
    return HYX 

def M_I(H_X, H_X_Y):
    MI = H_X - H_X_Y
    return MI

def M_I_per_Photon(M_I,n_OOK):
    MIperPhoton = M_I / (n_OOK/2)
    return MIperPhoton

In [8]:

# P_XY_OOK(P_XY(matrix_size(n_OOK)), K(n_OOK))

In [9]:
# P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))

In [10]:
# P_Y_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K)))

In [11]:
# P_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K)))

In [12]:
# H_X(P_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K)))

In [13]:
# H_Y(P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K)))

In [14]:
# H_XY(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))

In [15]:
# H_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))))

In [16]:
# H_Y_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_Y_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))))

In [17]:
# M_I(H_X(P_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))), H_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K)))))

In [18]:
# M_I_per_Photon(M_I(H_X(P_X(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))), H_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_X_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K), P_Y(P_XY_OOK(P_XY(matrix_size(n_OOK)), K))))),M(n_OOK/2))

In [19]:
n_OOK = 2
m = 1
o = 0
p = 0.1
q = 1 - p
print('Loss Bit for M = 1')
print('Number of Time Bin:', M(n_OOK/2))
print('Number of Code word:', K(n_OOK))
print('Matrix Size:',matrix_size(n_OOK))

print('Joint Probability P(X,Y):')
print(P_XY(matrix_size(n_OOK)))


# print('Probability P(X):', PX)
# print('Probability P(Y):', PY)

# print('Conditional Probability P(X|Y):')
# print(P_X_Y)
# print('Conditional Probability P(Y|X):')
# print(P_Y_X)

# print('Entropy H(X):', HX)
# print('Entropy H(Y):', HY)

# print('Joint Entropy H(X,Y):', H_XY)
# print('Conditional Entropy H(X|Y):', H_X_Y)
# print('Conditional Entropy H(Y|X):', H_Y_X)

# print('Mutual Information I(X;Y)):', MI)
# print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 1
Number of Time Bin: 2.0
Number of Code word: 4
Matrix Size: 4
Joint Probability P(X,Y):
[[1.   0.   0.   0.  ]
 [0.1  0.9  0.   0.  ]
 [0.1  0.   0.9  0.  ]
 [0.01 0.09 0.09 0.81]]


In [27]:
matrix = [[1, 0, 0, 0], [0.1, 0.9, 0, 0], [0.1, 0, 0.9, 0], [0.01, 0.09, 0.09, 0.81]]

# Initialize count variables
count_m = 0
count_o = 0
count_p = 0
count_q = 0

for row in matrix:
    for element in row:
        if element == 1:
            count_m += 1
        elif element == 0:
            count_o += 1
        elif element == 0.1:
            count_p += 1
        elif element == 0.9:
            count_q += 1

print("Count of 'm':", count_m)
print("Count of 'o':", count_o)
print("Count of 'p':", count_p)
print("Count of 'q':", count_q)


Count of 'm': 1
Count of 'o': 7
Count of 'p': 2
Count of 'q': 2


In [20]:
import numpy as np

def M(n):
    return 2 * n

def K(M):
    return 2 ** M

def matrix_size(n):
    return 2 ** n

def P_XY(matrix_size, p, q):
    matrix = np.zeros((matrix_size, matrix_size))
    
    # Calculate (p + q)^n
    pq_sum = p + q
    pq_pow_n = pq_sum ** n
    
    # Assign the value to the last row elements
    matrix[-1, :-1] = pq_pow_n * p
    matrix[-1, -1] = pq_pow_n * q
    
    for i in range(matrix_size - 1):
        for j in range(matrix_size - 1):
            row_binary = bin(i)[2:].zfill(n)  # Binary representation of row index
            col_binary = bin(j)[2:].zfill(n)  # Binary representation of column index

            m = 1.0  # Default value for 'm'
            for k in range(n):
                if row_binary[k] == '0' and col_binary[k] == '1':
                    m *= q  # Update value to 'q'
                elif row_binary[k] == '1' and col_binary[k] == '0':
                    m *= p  # Update value to 'p'

            matrix[i, j] = m
    
    return matrix

# Example usage
n = 2
p = 0.1
q = 0.9

matrix_size_val = matrix_size(n)
P_XY_val = P_XY(matrix_size_val, p, q)

print(P_XY_val)


[[1.   0.9  0.9  0.  ]
 [0.1  1.   0.09 0.  ]
 [0.1  0.09 1.   0.  ]
 [0.1  0.1  0.1  0.9 ]]


In [21]:
import numpy as np

def M(n):
    return 2 * n

def K(M):
    return 2 ** M

def matrix_size(n):
    return 2 ** n


def calculate_entropy(probabilities):
    # Calculate the entropy
    non_zero_probs = probabilities[probabilities != 0]
    entropy = -np.sum(non_zero_probs * np.log2(non_zero_probs))
    return entropy

def calculate_mutual_information(probabilities, p_x, p_y):
    # Calculate the mutual information
    non_zero_probs = probabilities[probabilities != 0]
    mutual_info = np.sum(non_zero_probs * np.log2(non_zero_probs / (p_x * p_y)))
    return mutual_info

def calculate_entropy_and_mutual_info(n, p, q):
    matrix_size_val = matrix_size(n)
    non_zero_indices = np.nonzero(P_XY(matrix_size_val, p, q))
    non_zero_probs = P_XY(matrix_size_val, p, q)[non_zero_indices]
    non_zero_probs = non_zero_probs.reshape(-1, 1)  # Reshape to have two dimensions
    non_zero_p_x = np.sum(non_zero_probs, axis=1)
    non_zero_p_y = np.sum(non_zero_probs, axis=0)
    
    entropy_x = calculate_entropy(non_zero_p_x)
    entropy_y = calculate_entropy(non_zero_p_y)
    mutual_info = calculate_mutual_information(non_zero_probs, non_zero_p_x, non_zero_p_y)
    
    return entropy_x, entropy_y, mutual_info

# Example usage
n = 3
p = 0.1
q = 0.9

entropy_x, entropy_y, mutual_info = calculate_entropy_and_mutual_info(n, p, q)

print("Entropy X:", entropy_x)
print("Entropy Y:", entropy_y)
print("Mutual Information:", mutual_info)


Entropy X: 12.437599427179277
Entropy Y: -94.63675798797689
Mutual Information: -94.6367579879769


In [22]:
import numpy as np

def M(n):
    return 2 * n

def K(M):
    return 2 ** M

def matrix_size(n):
    return 2 ** n

def P_XY(matrix_size, p, q):
    # Generate the joint probability matrix P(X, Y)
    P_XY = np.zeros((matrix_size, matrix_size))
    P_XY[0, 0] = p * q
    P_XY[0, 1] = (1 - p) * q
    P_XY[1, 0] = p * (1 - q)
    P_XY[1, 1] = (1 - p) * (1 - q)
    return P_XY

def calculate_entropy(probabilities):
    # Calculate the entropy
    non_zero_probs = probabilities[probabilities != 0]
    entropy = -np.sum(non_zero_probs * np.log2(non_zero_probs))
    return entropy

def calculate_mutual_information(probabilities, p_x, p_y):
    # Calculate the mutual information
    non_zero_probs = probabilities[probabilities != 0]
    mutual_info = np.sum(non_zero_probs * np.log2(non_zero_probs / (p_x * p_y)))
    return mutual_info

def calculate_entropy_and_mutual_info(n, p, q):
    matrix_size_val = matrix_size(n)
    joint_probs = P_XY(matrix_size_val, p, q)
    non_zero_indices = np.nonzero(joint_probs)
    non_zero_probs = joint_probs[non_zero_indices]
    non_zero_probs = non_zero_probs / np.sum(non_zero_probs)  # Normalize the probabilities
    non_zero_p_x = np.sum(non_zero_probs, axis=1, keepdims=True)
    non_zero_p_y = np.sum(non_zero_probs, axis=0)
    
    entropy_x = calculate_entropy(non_zero_p_x)
    entropy_y = calculate_entropy(non_zero_p_y)
    mutual_info = calculate_mutual_information(non_zero_probs, non_zero_p_x, non_zero_p_y)
    
    return entropy_x, entropy_y, mutual_info

# Example usage
n = 3
p = 0.1
q = 0.9

entropy_x, entropy_y, mutual_info = calculate_entropy_and_mutual_info(n, p, q)

print("Entropy X:", entropy_x)
print("Entropy Y:", entropy_y)
print("Mutual Information:", mutual_info)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
import numpy as np

def M(n):
    return 2 * n

def K(M):
    return 2 ** M

def matrix_size(n):
    return 2 ** n

def calculate_entropy(probabilities):
    # Calculate the entropy
    non_zero_probs = probabilities[probabilities != 0]
    entropy = -np.sum(non_zero_probs * np.log2(non_zero_probs))
    return entropy

def calculate_mutual_information(probabilities, p_x, p_y):
    # Calculate the mutual information
    non_zero_probs = probabilities[probabilities != 0]
    p_x_non_zero = p_x[probabilities != 0]
    p_y_non_zero = p_y[probabilities != 0]
    mutual_info = np.sum(non_zero_probs * np.log2(non_zero_probs / (p_x_non_zero[:, None] * p_y_non_zero)))
    return mutual_info

def calculate_entropy_and_mutual_info(n, p, q):
    matrix_size_val = matrix_size(n)
    non_zero_indices = np.nonzero(P_XY(matrix_size_val, p, q))
    non_zero_probs = P_XY(matrix_size_val, p, q)[non_zero_indices]
    non_zero_p_x = np.sum(non_zero_probs, axis=1)
    non_zero_p_y = np.sum(non_zero_probs, axis=0)

    entropy_x = calculate_entropy(non_zero_p_x)
    entropy_y = calculate_entropy(non_zero_p_y)
    mutual_info = calculate_mutual_information(non_zero_probs, non_zero_p_x, non_zero_p_y)

    return entropy_x, entropy_y, mutual_info

# Example usage
n = 3
p = 0.1
q = 0.9

entropy_x, entropy_y, mutual_info = calculate_entropy_and_mutual_info(n, p, q)

print("Entropy X:", entropy_x)
print("Entropy Y:", entropy_y)
print("Mutual Information:", mutual_info)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
import numpy as np

def P_XY(M, p, q):
    n = int(np.log2(M))
    matrix = np.zeros((M, M))

    for i in range(M):
        for j in range(M):
            x = i // (2 ** (n-1))
            y = j // (2 ** (n-1))
            if x == y:
                matrix[i, j] = p
            else:
                matrix[i, j] = q

    return matrix

def calculate_entropy(probabilities):
    non_zero_probs = probabilities[probabilities != 0]
    entropy = -np.sum(non_zero_probs * np.log2(non_zero_probs))
    return entropy

def calculate_mutual_information(probabilities, p_x, p_y):
    non_zero_probs = probabilities[probabilities != 0]
    p_x_non_zero = p_x[probabilities != 0]
    p_y_non_zero = p_y[probabilities != 0]
    mutual_info = np.sum(non_zero_probs * np.log2(non_zero_probs / (p_x_non_zero[:, None] * p_y_non_zero)))
    return mutual_info

def calculate_entropy_and_mutual_info(n, p, q):
    matrix_size_val = matrix_size(n)
    probabilities = P_XY(matrix_size_val, p, q)
    non_zero_indices = np.nonzero(probabilities)
    non_zero_probs = probabilities[non_zero_indices]
    non_zero_p_x = np.sum(non_zero_probs, axis=1)
    non_zero_p_y = np.sum(non_zero_probs, axis=0)
    entropy_x = calculate_entropy(non_zero_p_x)
    entropy_y = calculate_entropy(non_zero_p_y)
    mutual_info = calculate_mutual_information(non_zero_probs, non_zero_p_x, non_zero_p_y)
    return entropy_x, entropy_y, mutual_info

# Example usage
n = 3
p = 0.1
q = 0.9

entropy_x, entropy_y, mutual_info = calculate_entropy_and_mutual_info(n, p, q)

print("Entropy X:", entropy_x)
print("Entropy Y:", entropy_y)
print("Mutual Information:", mutual_info)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# print('Loss Bit for M = 1')
# print('Number of Time Bin', M)

# print('Joint Probability P(X,Y):')
# print(P_XY_OOK)

# print('Probability P(X):', PX)
# print('Probability P(Y):', PY)

# print('Conditional Probability P(X|Y):')
# print(P_X_Y)
# print('Conditional Probability P(Y|X):')
# print(P_Y_X)

# print('Entropy H(X):', HX)
# print('Entropy H(Y):', HY)

# print('Joint Entropy H(X,Y):', H_XY)
# print('Conditional Entropy H(X|Y):', H_X_Y)
# print('Conditional Entropy H(Y|X):', H_Y_X)

# print('Mutual Information I(X;Y)):', MI)
# print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

In [ ]:

# IperTimeBin_AB_OOK_list_0 = []
# IperPhotonTimeBin_AB_OOK_list_0 = []

# IperTimeBin_AB_OOK_list_0_1 = []
# IperPhotonTimeBin_AB_OOK_list_0_1 = []

I_AB_OOK_list_0 = []
IperPhoton_AB_OOK_list_0 = []
TimeBin_OOK_list_0 = []

# for n_OOK in range(1, 12):
#     m = 1
#     o = 0
#     p = 0
#     q = 1 - p
#     M_val = M(n_OOK)
#     K_val = K(n_OOK)
#     matrix_size_val = matrix_size(n_OOK)
#     P_XY_val = P_XY(matrix_size_val)
#     P_XY_OOK_val = P_XY_OOK(P_XY_val, K_val)
#     P_X_val = P_X(P_XY_OOK_val)
#     P_Y_val = P_Y(P_XY_OOK_val)
#     P_X_Y_val = P_X_Y(P_XY_OOK_val, P_Y_val)
#     H_X_val = H_X(P_X_val)
#     H_X_Y_val = H_X_Y(P_XY_OOK_val, P_X_Y_val)
#     I_val = M_I(H_X_val, H_X_Y_val)
#     IperPhoton_AB_OOK_val = M_I_per_Photon(I_val,n_OOK)
    
#     TimeBin_OOK_list_0.append(M_val)
#     I_AB_OOK_list_0.append(I_val)
#     IperPhoton_AB_OOK_list_0.append(IperPhoton_AB_OOK_val)

    # IperTimeBin_AB_OOK_val = I_AB_OOK_diagonal(P_AB_OOK_val, n_OOK, P_D_OOK_val) / M_OOK
    # IperTimeBin_AB_OOK_list_0.append(IperTimeBin_AB_OOK_val)
    # IperPhotonTimeBin_AB_OOK_val = I_AB_OOK_diagonal(P_AB_OOK_val, n_OOK, P_D_OOK_val)/ (n_OOK * M_OOK)
    # IperPhotonTimeBin_AB_OOK_list_0.append(IperPhotonTimeBin_AB_OOK_val)

I_AB_OOK_list_0_1 = []
IperPhoton_AB_OOK_list_0_1 = []
TimeBin_OOK_list_0_1 = []

for n_OOK in range(1, 12):
    m = 1
    o = 0
    p = 0.1
    q = 1 - p
    M_val = M(n_OOK)
    K_val = K(n_OOK)
    matrix_size_val = matrix_size(n_OOK)
    P_XY_val = P_XY(matrix_size_val)
    P_XY_OOK_val = P_XY_OOK(P_XY_val, K_val)
    P_X_val = P_X(P_XY_OOK_val)
    P_Y_val = P_Y(P_XY_OOK_val)
    P_X_Y_val = P_X_Y(P_XY_OOK_val, P_Y_val)
    H_X_val = H_X(P_X_val)
    H_X_Y_val = H_X_Y(P_XY_OOK_val, P_X_Y_val)
    I_val = M_I(H_X_val, H_X_Y_val)
    IperPhoton_AB_OOK_val = M_I_per_Photon(I_val,n_OOK)
    
    TimeBin_OOK_list_0_1.append(M_val)
    I_AB_OOK_list_0_1.append(I_val)
    IperPhoton_AB_OOK_list_0_1.append(IperPhoton_AB_OOK_val)

I_AB_OOK_list_0_2 = []
IperPhoton_AB_OOK_list_0_2 = []
TimeBin_OOK_list_0_2 = []

# for n_OOK in range(1, 12):
#     m = 1
#     o = 0
#     p = 0.2
#     q = 1 - p
#     M_val = M(n_OOK)
#     K_val = K(n_OOK)
#     matrix_size_val = matrix_size(n_OOK)
#     P_XY_val = P_XY(matrix_size_val)
#     P_XY_OOK_val = P_XY_OOK(P_XY_val, K_val)
#     P_X_val = P_X(P_XY_OOK_val)
#     P_Y_val = P_Y(P_XY_OOK_val)
#     P_X_Y_val = P_X_Y(P_XY_OOK_val, P_Y_val)
#     H_X_val = H_X(P_X_val)
#     H_X_Y_val = H_X_Y(P_XY_OOK_val, P_X_Y_val)
#     I_val = M_I(H_X_val, H_X_Y_val)
#     IperPhoton_AB_OOK_val = M_I_per_Photon(I_val,n_OOK)
    
#     TimeBin_OOK_list_0_2.append(M_val)
#     I_AB_OOK_list_0_2.append(I_val)
#     IperPhoton_AB_OOK_list_0_2.append(IperPhoton_AB_OOK_val)


# I_AB_OOK_list_0_9 = []
# IperPhoton_AB_OOK_list_0_9 = []
# TimeBin_OOK_list_0_9= []

# for n_OOK in range(1, 12):
#     m = 1
#     o = 0
#     p = 0.9
#     q = 1 - p
#     M_val = M(n_OOK)
#     K_val = K(n_OOK)
#     matrix_size_val = matrix_size(n_OOK)
#     P_XY_val = P_XY(matrix_size_val)
#     P_XY_OOK_val = P_XY_OOK(P_XY_val, K_val)
#     P_X_val = P_X(P_XY_OOK_val)
#     P_Y_val = P_Y(P_XY_OOK_val)
#     P_X_Y_val = P_X_Y(P_XY_OOK_val, P_Y_val)
#     H_X_val = H_X(P_X_val)
#     H_X_Y_val = H_X_Y(P_XY_OOK_val, P_X_Y_val)
#     I_val = M_I(H_X_val, H_X_Y_val)
#     IperPhoton_AB_OOK_val = M_I_per_Photon(I_val,n_OOK)
    
#     TimeBin_OOK_list_0_9.append(M_val)
#     I_AB_OOK_list_0_9.append(I_val)
#     IperPhoton_AB_OOK_list_0_9.append(IperPhoton_AB_OOK_val)




In [ ]:
figure, axis = plt.subplots(1,1,figsize=(20,10))

plt.scatter(TimeBin_OOK_list_0, IperPhoton_AB_OOK_list_0, label='I_AB_OOK per Photonat at P = 0', color ='blue', linewidth=3, alpha=1)
plt.scatter(TimeBin_OOK_list_0_1, IperPhoton_AB_OOK_list_0_1, label='I_AB_OOK per Photon at P = 0.1', color ='red', linewidth=3, alpha=1)
plt.scatter(TimeBin_OOK_list_0_2, IperPhoton_AB_OOK_list_0_2, label='I_AB_OOK per Photon at P = 0.2', color ='green', linewidth=3, alpha=1)
plt.scatter(TimeBin_OOK_list_0_9, IperPhoton_AB_OOK_list_0_9, label='I_AB_OOK per Photon at P = 0.9', color ='orange', linewidth=3, alpha=1)
plt.ylim(0, 30) 
plt.ylim(0, 2.5) 
plt.title('Mutual Information per Photon ($\\frac{I_{AB}}{n}$) of OOK  (1 \u2264 n \u2264 11) Vs. Number of Time Bin (M) (2 \u2264 n \u2264 20) at Probability P = 0, 0.1', fontsize='x-large')
plt.xlabel('M (s) ', fontsize = 14)
plt.ylabel('$\\frac{I_{AB}}{n}$ (Bit/Joule)', fontsize = 14)
plt.grid(True)
plt.legend(fontsize=14)

for index in range(0,11): # len(TimeBin_OOK_list_0)
  plt.text(TimeBin_OOK_list_0[index], IperPhoton_AB_OOK_list_0[index], round(IperPhoton_AB_OOK_list_0[index],2), size=12)

for index in range(0,11): # (len(TimeBin_OOK_list_0_1)
  plt.text(TimeBin_OOK_list_0_1[index], IperPhoton_AB_OOK_list_0_1[index], round(IperPhoton_AB_OOK_list_0_1[index],2), size=12)


for index in range(0,11): # (len(TimeBin_OOK_list_0_1)
  plt.text(TimeBin_OOK_list_0_2[index], IperPhoton_AB_OOK_list_0_2[index], round(IperPhoton_AB_OOK_list_0_2[index],2), size=12)

for index in range(0,11): # (len(TimeBin_OOK_list_0_1)
  plt.text(TimeBin_OOK_list_0_9[index], IperPhoton_AB_OOK_list_0_9[index], round(IperPhoton_AB_OOK_list_0_9[index],2), size=12)

## Loss Bit for M = 1

In [ ]:
# Conditional probability matrix [P(Y|X)]
n = 1
o = 0
p = 0.1
q = 0.9
M = 1
K = 2**M

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = np.array([[n, o],
                  [p, q]]) * 1/ (K)

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))
H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [ ]:
P_XY

In [ ]:
print('Loss Bit for M = 1')
print('Number of Time Bin', M)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)

print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):', H_XY)
print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

## Loss Bit for M = 2

In [23]:
m = 1
o = 0
p = 0.1
q = 0.9
M = 2
K = 2**M

P_XY = np.array([[m*m, m*o, o*m, o*o],
                 [m*p, m*q, o*p, o*q],
                 [p*m, p*o, q*m, q*o],
                 [p*p, p*q, q*p, q*q]]) # * 1/K

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))

H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [24]:
print('Loss Bit for M = 2')
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):', H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 2
Number of Time Bin 2
Probability P(X): [1. 1. 1. 1.]
Probability P(Y): [1.21 0.99 0.99 0.81]
Joint Probability P(X,Y):
[[1.   0.   0.   0.  ]
 [0.1  0.9  0.   0.  ]
 [0.1  0.   0.9  0.  ]
 [0.01 0.09 0.09 0.81]]
Conditional Probability P(X|Y):
[[0.82644628 0.         0.         0.        ]
 [0.08264463 0.90909091 0.         0.        ]
 [0.08264463 0.         0.90909091 0.        ]
 [0.00826446 0.09090909 0.09090909 1.        ]]
Conditional Probability P(Y|X):
[[1.   0.   0.   0.  ]
 [0.1  0.9  0.   0.  ]
 [0.1  0.   0.9  0.  ]
 [0.01 0.09 0.09 0.81]]
Entropy H(X): -0.0
Entropy H(Y): -0.05780436809753403
Joint Entropy H(X,Y): 1.8759823730586993
Conditional Entropy H(X|Y): 1.9337867410682286
Conditional Entropy H(Y|X): 1.875982373058699
Mutual Information I(X;Y)): -1.9337867410682286
Mutual Information per Photon I(X;Y)/(M/2)): -1.9337867410682286


-(0.25 * np.log2(0.25) + 0.025 * np.log2(0.025)  + 0.225 * np.log2(0.225)

 + 0.025* np.log2(0.025) + 0.225* np.log2(0.225) + 0.0025* np.log2(0.0025) + 0.0225* np.log2(0.0225) + 0.0225* np.log2(0.0225) + 0.2025* np.log2(0.2025))

In [ ]:
-(0.25 * np.log2(0.25) + 0.025 * np.log2(0.025)  + 0.225 * np.log2(0.225) + 0.025* np.log2(0.025) + 0.225* np.log2(0.225) + 0.0025* np.log2(0.0025) + 0.0225* np.log2(0.0225) + 0.0225* np.log2(0.0225) + 0.2025* np.log2(0.2025))

In [ ]:
-(0.25 * np.log2(0.83) + 0.025 * np.log2(0.082)  + 0.225 * np.log2(0.91) + 0.025* np.log2(0.082) + 0.225* np.log2(0.91) + 0.0025* np.log2(0.0082) + 0.0225* np.log2(0.091) + 0.0225* np.log2(0.091) + 0.2025* np.log2(1))

In [ ]:
-(0.25 *  np.log2(1) + 0.025 *  np.log2(0.1)  + 0.225 *  np.log2(0.9) + 0.025*  np.log2(0.1) + 0.225*  np.log2(0.9) + 0.0025*  np.log2(0.1) + 0.0225*  np.log2(0.09) + 0.0225*  np.log2(0.09) + 0.2025*  np.log2(0.81))

In [ ]:
2 - 0.48

In [ ]:
1.9855 - 0.46

## Loss Bit for M = 3

In [ ]:
n = 1       # 0 to 0 
o = 0       # 0 to 1
p = 0.1     # 1 to 0 
q = 0.9     # 1 to 1
M = 3
K = 2**M

# Conditional probability matrix [P(Y|X)]
# Consider the flip bit case for M = 3 
P_XY = np.array([ [n*n*n, n*n*o, n*o*n, n*o*o, o*n*n, o*n*o, o*o*n, o*o*o],
                  [n*n*p, n*n*q, n*o*p, n*o*q, o*n*p, o*n*q, o*o*p, o*o*q],
                  [n*p*n, n*p*o, n*q*n, n*p*o, o*p*n, o*p*o, o*q*n, o*q*o],
                  [n*p*p, n*p*q, n*q*p, n*q*q, o*p*p, o*p*q, o*q*p, o*q*q],
                  [p*n*n, p*n*o, p*o*n, p*o*o, q*n*n, q*n*o, q*o*n, q*o*o],
                  [p*n*p, p*n*q, p*o*p, p*o*q, q*n*p, q*n*q, q*o*p, q*o*q],

                  [p*p*n, p*p*o, p*q*n, p*q*o, q*p*n, q*p*o, q*q*n, q*q*o],
                  [p*p*p, p*p*q, p*q*p, p*q*q, q*p*p, q*p*q, q*q*p, q*q*q]]) * 1/ (K)

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

# Calculate Joint Probability Matrix [P(X,Y)]
P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))
H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [ ]:
print('Loss Bit for M = 3')
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

# print('Conditional Probability P(X|Y):')
# print(P_X_Y)
# print('Conditional Probability P(Y|X):')
# print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

# print('Joint Entropy H(X,Y):')
# print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 3
Number of Time Bin 3
Probability P(X): [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
Probability P(Y): [0.166375 0.136125 0.136125 0.111375 0.136125 0.111375 0.111375 0.091125]
Joint Probability P(X,Y):
[[0.125    0.       0.       0.       0.       0.       0.       0.      ]
 [0.0125   0.1125   0.       0.       0.       0.       0.       0.      ]
 [0.0125   0.       0.1125   0.       0.       0.       0.       0.      ]
 [0.00125  0.01125  0.01125  0.10125  0.       0.       0.       0.      ]
 [0.0125   0.       0.       0.       0.1125   0.       0.       0.      ]
 [0.00125  0.01125  0.       0.       0.01125  0.10125  0.       0.      ]
 [0.00125  0.       0.01125  0.       0.01125  0.       0.10125  0.      ]
 [0.000125 0.001125 0.001125 0.010125 0.001125 0.010125 0.010125 0.091125]]
Entropy H(X): 3.0
Entropy H(Y): 2.978323361963425
Conditional Entropy H(X|Y): 0.7251700278832555
Conditional Entropy H(Y|X): 0.7034933898970123
Mutual Information I(X;Y)): 2

# I have not checked the codes below yet

# Another Way of Calculation starting from Joint Probability

## Marginal Probability P(X), P(Y), Conditional Probability P(X|Y), P(Y|X)

In [ ]:
# Calculate the column sums, probability P(X)
def P_X(P_XY):
    column_sums = np.sum(P_XY, axis=1)
    return column_sums 

# Calculate the column sums, probability P(Y)
def P_Y(P_XY):
    row_sums = np.sum(P_XY, axis=0)
    return row_sums

# Calculate the conditional probability matrix
def P_Y_X(P_XY, P_X): 
    P_YbyX = P_XY / P_X
    return P_YbyX

def P_X_Y(P_XY, P_Y):
    P_XbyY = P_XY / P_Y
    return P_XbyY

def M(P_XY): 
    return np.shape(P_XY)[0] / 2

## Marginal Entropy H(X), H(Y), Joint Entropy H(X,Y), Conditional Entropy H(X|Y), H(Y|X), Mutual Information

In [ ]:
def H_X(P_X):
    HX = np.sum(-(P_X) * np.log2(P_X))
    return HX

def H_Y(P_Y):
    HY = np.sum(-(P_Y) * np.log2(P_Y))
    return HY

# Calculate the joint entropy H(X,Y)
def H_XY(P_XY):
    HXY = -np.sum(P_XY * np.log2(P_XY + 1e-10), axis=0).sum()
    return HXY

# Calculate the conditional entropy H(Y|X)
def H_Y_X(P_Y_X): 
    H_YbyX = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()
    return H_YbyX

def H_X_Y(P_X_Y): 
    H_XbyY = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
    return H_XbyY

def MutualInformation(H_Y, H_Y_X):
    MI = H_Y - H_Y_X
    return MI 

def MIperPhoton(MutualInformation, M):
    return MutualInformation / (M/2)

## Number into Fraction

In [ ]:
from fractions import Fraction
fraction_HX = Fraction(H_X(P_X(P_XY))).limit_denominator()
fraction_HY = Fraction(H_Y(P_Y(P_XY))).limit_denominator()
fraction_HXY = Fraction(H_XY((P_XY))).limit_denominator()
fraction_HXbyY = Fraction(H_X_Y(P_X_Y(P_XY, P_Y(P_XY)))).limit_denominator()
fraction_HYbyX = Fraction(H_Y_X(P_Y_X(P_XY, P_X(P_XY)))).limit_denominator()
fraction_MI = Fraction(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X(P_Y_X(P_XY, P_X(P_XY))))).limit_denominator()

## Flip Bit Joint Probability of OOK for M = 1 

In [ ]:
P_XY = np.array([[0.45, 0.05],
                [0.05, 0.45]])

In [ ]:
M(P_XY)

In [ ]:
print('Flip Bit for M = 1')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

In [ ]:
# Flip Bit Joint Prbability of OOK for M = 2
P_XY = np.array([[0.2025, 0.0225, 0.0225, 0.0025],
                 [0.0225, 0.2025, 0.0025, 0.0225],
                 [0.0225, 0.0025, 0.2025, 0.0225],
                 [0.0025, 0.0225, 0.0225, 0.2025]])

In [ ]:
print('Flip Bit for M = 2')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

In [ ]:
# Loss Bit Joint Prbability of OOK for M = 1
# P_XY = np.array([[0.5, 0],
#                  [0.05, 0.45]])

P_XY = np.array([[1, 0], 
                 [0.1, 0.9]]) * 1/2

In [ ]:
M(P_XY)

In [ ]:
print('Loss Bit for M = 1')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

In [ ]:
- (0.55 * np.log2(0.55) + 0.45 * np.log2(0.45))

In [ ]:
-(0.5 * np.log2(0.5) + 0 + 0.05 * np.log2(0.05) + 0.45 * np.log2(0.45))

In [ ]:
# Loss Bit Joint Prbability of OOK for M = 2
P_XY = np.array([[0.25, 0, 0, 0],
                [0.025, 0.225, 0, 0],
                [0.025, 0, 0.225, 0],
                [0.0025, 0.00225, 0.225, 0.2025]])


In [ ]:
print('Flip Bit for M = 2')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Conditional Probability P(X|Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

## Other Calculation

In [ ]:
# Example from Textbook Elements of Information Theory Chapter 2
P_XY = np.array([[1/8, 1/16, 1/32, 1/32],
                 [1/16, 1/8, 1/32, 1/32],
                 [1/16, 1/16, 1/16, 1/16],
                 [1/4, 0, 0, 0]])

In [ ]:
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Conditional Probability P(X|Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

In [ ]:
-(0.5 * np.log2(0.5) + 0.25 * np.log2(0.25) + 0.125 * np.log2(0.125) + 0.125 * np.log2(0.125))

In [ ]:
-(0.25 * np.log2(0.25) + 0.25 * np.log2(0.25) + 0.25 * np.log2(0.25) + 0.25 * np.log2(0.25))

In [ ]:
1/16

In [ ]:
0.0625 / 0.25

In [ ]:
0.03125 / 0.25

In [ ]:
1/32

In [ ]:
-(0.125 * np.log2(0.5) + 0.0625 * np.log2(0.25) + 0.03125 * np.log2(0.125) + 0.03125 * np.log2(0.125) + 0.0625 * np.log2(0.25) + 0.125 * np.log2(0.5) +  0.0625* np.log2(0.125) + 0.25  * np.log2(0.25))

In [ ]:
1.75 - 1.375