In [1]:
import numpy as np
import matplotlib.pyplot as plt
import itertools
import math
from pyparsing import python_style_comment
from itertools import islice
import scipy.sparse as sps
from scipy.sparse import diags
from functools import lru_cache
import pandas as pd

# Working on Mutual Information Starting from Conditional Probability

## Flip Bit for M = 1 

In [137]:
# Conditional probability matrix [P(Y|X)]
p = 0.1
q = 0.9

# Consider the Flip Bit case for M = 1 
P_Y_X = np.array([[q, p],
                  [p, q]])

M = np.shape(P_Y_X)[0] / 2

# Marginal probabilities P(X) and P(Y)
# prob_x = np.array([1/4, 1/4])
# prob_y = np.array([1/4, 1/4])

# PX = np.sum(prob_x, axis = 0).sum()
# PY = np.sum(prob_y, axis = 0).sum()
PX = 0.5
PY = 0.5

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = PX * P_Y_X
P_X_Y = P_XY / PY

# Entropy
# HX = np.sum(-(prob_x) * np.log2(prob_x))
HX = - np.log2(PX)
HY = - np.log2(PY)

H_XY = - np.log2(P_XY)
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [138]:
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):')
print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Number of Time Bin 1.0
Probability P(X): 0.5
Probability P(Y): 0.5
Joint Probability P(X,Y):
[[0.45 0.05]
 [0.05 0.45]]
Conditional Probability P(X|Y):
[[0.9 0.1]
 [0.1 0.9]]
Conditional Probability P(Y|X):
[[0.9 0.1]
 [0.1 0.9]]
Entropy H(X): 1.0
Entropy H(Y): 1.0
Joint Entropy H(X,Y):
[[1.15200309 4.32192809]
 [4.32192809 1.15200309]]
Conditional Entropy H(X|Y): 0.4689955933007422
Conditional Entropy H(Y|X): 0.4689955933007422
Mutual Information I(X;Y)): 0.5310044066992579
Mutual Information per Photon I(X;Y)/(M/2)): 1.0620088133985157


## Flip Bit for M = 2

In [139]:
p = 0.1
q = 0.9

# Conditional probability matrix [P(Y|X)]
# Consider the flip bit case for M = 2 
P_Y_X = np.array([[q*q, q*p, p*q, p*p],
                  [q*p, q*q, p*p, p*q],
                  [p*q, p*p, q*q, q*p],
                  [p*p, p*q, q*p, q*q]])

M = np.shape(P_Y_X)[0] / 2

# Marginal probabilities P(X) and P(Y)
# prob_x = np.array([1/4, 0])
# prob_y = np.array([1/8, 1/8])

# PX = np.sum(prob_x, axis = 0).sum()
# PY = np.sum(prob_y, axis = 0).sum()
PX = 1/4
PY = 1/4

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = PX * P_Y_X 
P_X_Y = P_XY / PY

# Entropy
HX = - np.log2(PX)
HY = - np.log2(PY)

H_XY = - np.log2(P_XY)
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [140]:
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):')
print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Number of Time Bin 2.0
Probability P(X): 0.25
Probability P(Y): 0.25
Joint Probability P(X,Y):
[[0.2025 0.0225 0.0225 0.0025]
 [0.0225 0.2025 0.0025 0.0225]
 [0.0225 0.0025 0.2025 0.0225]
 [0.0025 0.0225 0.0225 0.2025]]
Conditional Probability P(X|Y):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Conditional Probability P(Y|X):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Entropy H(X): 2.0
Entropy H(Y): 2.0
Joint Entropy H(X,Y):
[[2.30400619 5.47393119 5.47393119 8.64385619]
 [5.47393119 2.30400619 8.64385619 5.47393119]
 [5.47393119 8.64385619 2.30400619 5.47393119]
 [8.64385619 5.47393119 5.47393119 2.30400619]]
Conditional Entropy H(X|Y): 0.9379911866014845
Conditional Entropy H(Y|X): 0.9379911866014845
Mutual Information I(X;Y)): 1.0620088133985155
Mutual Information per Photon I(X;Y)/(M/2)): 1.0620088133985155


## Loss Bit for M = 1

In [141]:
# Conditional probability matrix [P(Y|X)]
n = 1
o = 0
p = 0.1
q = 0.9
M = 1
K = 2**M

# Calculate Joint Probability Matrix [P(X,Y)]
P_XY = np.array([[n, o],
                  [p, q]]) * 1/ (K)

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))
H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [142]:
print('Loss Bit for M = 1')
print('Number of Time Bin', M)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)

print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):', H_XY)
print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 1
Number of Time Bin 1
Joint Probability P(X,Y):
[[0.5  0.  ]
 [0.05 0.45]]
Probability P(X): [0.5 0.5]
Probability P(Y): [0.55 0.45]
Conditional Probability P(X|Y):
[[0.90909091 0.        ]
 [0.09090909 1.        ]]
Conditional Probability P(Y|X):
[[1.  0. ]
 [0.1 0.9]]
Entropy H(X): 1.0
Entropy H(Y): 0.9927744539878083
Joint Entropy H(X,Y): 1.2344977963618322
Conditional Entropy H(X|Y): 0.2417233425832146
Conditional Entropy H(Y|X): 0.23449779657823633
Mutual Information I(X;Y)): 0.7582766574167854
Mutual Information per Photon I(X;Y)/(M/2)): 1.5165533148335708


## Loss Bit for M = 2

In [143]:
n = 1
o = 0
p = 0.1
q = 0.9
M = 2
K = 2**M

P_XY = np.array([[n*n, n*o, o*n, o*o],
                 [n*p, n*q, o*p, o*q],
                 [p*n, p*o, q*n, q*o],
                 [p*p, p*q, q*p, q*q]]) * 1/K

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))

H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [144]:
print('Loss Bit for M = 2')
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):', H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 2
Number of Time Bin 2
Probability P(X): [0.25 0.25 0.25 0.25]
Probability P(Y): [0.3025 0.2475 0.2475 0.2025]
Joint Probability P(X,Y):
[[0.25   0.     0.     0.    ]
 [0.025  0.225  0.     0.    ]
 [0.025  0.     0.225  0.    ]
 [0.0025 0.0225 0.0225 0.2025]]
Conditional Probability P(X|Y):
[[0.82644628 0.         0.         0.        ]
 [0.08264463 0.90909091 0.         0.        ]
 [0.08264463 0.         0.90909091 0.        ]
 [0.00826446 0.09090909 0.09090909 1.        ]]
Conditional Probability P(Y|X):
[[1.   0.   0.   0.  ]
 [0.1  0.9  0.   0.  ]
 [0.1  0.   0.9  0.  ]
 [0.01 0.09 0.09 0.81]]
Entropy H(X): 2.0
Entropy H(Y): 1.9855489079756166
Joint Entropy H(X,Y): 2.4689955922908555
Conditional Entropy H(X|Y): 0.48344668526705714
Conditional Entropy H(Y|X): 0.46899559326467477
Mutual Information I(X;Y)): 1.5165533147329429
Mutual Information per Photon I(X;Y)/(M/2)): 1.5165533147329429


## Loss Bit for M = 3

In [145]:
n = 1       # 0 to 0 
o = 0       # 0 to 1
p = 0.1     # 1 to 0 
q = 0.9     # 1 to 1
M = 3
K = 2**M

# Conditional probability matrix [P(Y|X)]
# Consider the flip bit case for M = 3 
P_XY = np.array([[n*n*n, n*n*o, n*o*n, n*o*o, o*n*n, o*n*o, o*o*n, o*o*o],
                  [n*n*p, n*n*q, n*o*p, n*o*q, o*n*p, o*n*q, o*o*p, o*o*q],
                  [n*p*n, n*p*o, n*q*n, n*p*o, o*p*n, o*p*o, o*q*n, o*q*o],
                  [n*p*p, n*p*q, n*q*p, n*q*q, o*p*p, o*p*q, o*q*p, o*q*q],
                  [p*n*n, p*n*o, p*o*n, p*o*o, q*n*n, q*n*o, q*o*n, q*o*o],
                  [p*n*p, p*n*q, p*o*p, p*o*q, q*n*p, q*n*q, q*o*p, q*o*q],

                  [p*p*n, p*p*o, p*q*n, p*q*o, q*p*n, q*p*o, q*q*n, q*q*o],
                  [p*p*p, p*p*q, p*q*p, p*q*q, q*p*p, q*p*q, q*q*p, q*q*q]]) * 1/ (K)

PX = np.sum(P_XY, axis=1)
PY = np.sum(P_XY, axis=0)

# Calculate Joint Probability Matrix [P(X,Y)]
P_Y_X = P_XY / PX [:, np.newaxis]  # Adjust dimensions for proper broadcasting division
P_X_Y = P_XY / PY

# Entropy
HX = -np.sum(PX * np.log2(PX))
HY = -np.sum(PY * np.log2(PY))
H_XY = -np.sum(P_XY * np.log2(P_XY + 1e-10))
H_X_Y = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
H_Y_X = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()

# Mutual Information
MI = HX - H_X_Y

# Mutual Information per Photon
MIperPhoton = MI / (M/2)

In [146]:
print('Loss Bit for M = 3')
print('Number of Time Bin', M)

print('Probability P(X):', PX)
print('Probability P(Y):', PY)

print('Joint Probability P(X,Y):')
print(P_XY)

print('Conditional Probability P(X|Y):')
print(P_X_Y)
print('Conditional Probability P(Y|X):')
print(P_Y_X)


print('Entropy H(X):', HX)
print('Entropy H(Y):', HY)

print('Joint Entropy H(X,Y):')
print(H_XY)

print('Conditional Entropy H(X|Y):', H_X_Y)
print('Conditional Entropy H(Y|X):', H_Y_X)

print('Mutual Information I(X;Y)):', MI)
print('Mutual Information per Photon I(X;Y)/(M/2)):', MIperPhoton)

Loss Bit for M = 3
Number of Time Bin 3
Probability P(X): [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
Probability P(Y): [0.166375 0.136125 0.136125 0.111375 0.136125 0.111375 0.111375 0.091125]
Joint Probability P(X,Y):
[[0.125    0.       0.       0.       0.       0.       0.       0.      ]
 [0.0125   0.1125   0.       0.       0.       0.       0.       0.      ]
 [0.0125   0.       0.1125   0.       0.       0.       0.       0.      ]
 [0.00125  0.01125  0.01125  0.10125  0.       0.       0.       0.      ]
 [0.0125   0.       0.       0.       0.1125   0.       0.       0.      ]
 [0.00125  0.01125  0.       0.       0.01125  0.10125  0.       0.      ]
 [0.00125  0.       0.01125  0.       0.01125  0.       0.10125  0.      ]
 [0.000125 0.001125 0.001125 0.010125 0.001125 0.010125 0.010125 0.091125]]
Conditional Probability P(X|Y):
[[7.51314801e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.51314801e-02

# I have not checked the codes below yet

# Another Way of Calculation starting from Joint Probability

## Marginal Probability P(X), P(Y), Conditional Probability P(X|Y), P(Y|X)

In [12]:
# Calculate the column sums, probability P(X)
def P_X(P_XY):
    column_sums = np.sum(P_XY, axis=1)
    return column_sums 

# Calculate the column sums, probability P(Y)
def P_Y(P_XY):
    row_sums = np.sum(P_XY, axis=0)
    return row_sums

# Calculate the conditional probability matrix
def P_Y_X(P_XY, P_X): 
    P_YbyX = P_XY / P_X
    return P_YbyX

def P_X_Y(P_XY, P_Y):
    P_XbyY = P_XY / P_Y
    return P_XbyY

def M(P_XY): 
    return np.shape(P_XY)[0] / 2

## Marginal Entropy H(X), H(Y), Joint Entropy H(X,Y), Conditional Entropy H(X|Y), H(Y|X), Mutual Information

In [13]:
def H_X(P_X):
    HX = np.sum(-(P_X) * np.log2(P_X))
    return HX

def H_Y(P_Y):
    HY = np.sum(-(P_Y) * np.log2(P_Y))
    return HY

# Calculate the joint entropy H(X,Y)
def H_XY(P_XY):
    HXY = -np.sum(P_XY * np.log2(P_XY + 1e-10), axis=0).sum()
    return HXY

# Calculate the conditional entropy H(Y|X)
def H_Y_X(P_Y_X): 
    H_YbyX = -np.sum(P_XY * np.log2(P_Y_X + 1e-10), axis=0).sum()
    return H_YbyX

def H_X_Y(P_X_Y): 
    H_XbyY = -np.sum(P_XY * np.log2(P_X_Y + 1e-10), axis=0).sum()
    return H_XbyY

def MutualInformation(H_Y, H_Y_X):
    MI = H_Y - H_Y_X
    return MI 

def MIperPhoton(MutualInformation, M):
    return MutualInformation / (M/2)

## Number into Fraction

In [14]:
from fractions import Fraction
fraction_HX = Fraction(H_X(P_X(P_XY))).limit_denominator()
fraction_HY = Fraction(H_Y(P_Y(P_XY))).limit_denominator()
fraction_HXY = Fraction(H_XY((P_XY))).limit_denominator()
fraction_HXbyY = Fraction(H_X_Y(P_X_Y(P_XY, P_Y(P_XY)))).limit_denominator()
fraction_HYbyX = Fraction(H_Y_X(P_Y_X(P_XY, P_X(P_XY)))).limit_denominator()
fraction_MI = Fraction(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X(P_Y_X(P_XY, P_X(P_XY))))).limit_denominator()

## Flip Bit Joint Probability of OOK for M = 1 

In [15]:
P_XY = np.array([[0.45, 0.05],
                [0.05, 0.45]])

In [16]:
M(P_XY)

1.0

In [17]:
print('Flip Bit for M = 1')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

Flip Bit for M = 1
Number of Time Bin 1.0
Probability P(X): [0.5 0.5]
Probability P(Y): [0.5 0.5]
Joint Probability P(X, Y):
[[0.45 0.05]
 [0.05 0.45]]
Conditional Probability P(X|Y):
[[0.9 0.1]
 [0.1 0.9]]
Conditional Probability P(Y|X):
[[0.9 0.1]
 [0.1 0.9]]
Entropy H(X): 1.0 3
Entropy H(Y): 1.0 2550791/856452
Joint Entropy H(X,Y): 1.4689955930122032 2580709/696831
Conditional Entropy H(X|Y): 0.4689955933007422 245771/338915
Conditional Entropy H(Y|X): 0.4689955933007422 682250/969803
Mutual Information I(X;Y)): 0.5310044066992579
Mutual Information per Photon I(X;Y) / (M/2)): 1.0620088133985157


In [18]:
# Flip Bit Joint Prbability of OOK for M = 2
P_XY = np.array([[0.2025, 0.0225, 0.0225, 0.0025],
                 [0.0225, 0.2025, 0.0025, 0.0225],
                 [0.0225, 0.0025, 0.2025, 0.0225],
                 [0.0025, 0.0225, 0.0225, 0.2025]])

In [19]:
print('Flip Bit for M = 2')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

Flip Bit for M = 2
Number of Time Bin 2.0
Probability P(X): [0.25 0.25 0.25 0.25]
Probability P(Y): [0.25 0.25 0.25 0.25]
Joint Probability P(X, Y):
[[0.2025 0.0225 0.0225 0.0025]
 [0.0225 0.2025 0.0025 0.0225]
 [0.0225 0.0025 0.2025 0.0225]
 [0.0025 0.0225 0.0225 0.2025]]
Conditional Probability P(X|Y):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Conditional Probability P(Y|X):
[[0.81 0.09 0.09 0.01]
 [0.09 0.81 0.01 0.09]
 [0.09 0.01 0.81 0.09]
 [0.01 0.09 0.09 0.81]]
Entropy H(X): 2.0 3
Entropy H(Y): 2.0 2550791/856452
Joint Entropy H(X,Y): 2.9379911848702505 2580709/696831
Conditional Entropy H(X|Y): 0.9379911866014844 245771/338915
Conditional Entropy H(Y|X): 0.9379911866014844 682250/969803
Mutual Information I(X;Y)): 1.0620088133985157
Mutual Information per Photon I(X;Y) / (M/2)): 1.0620088133985157


In [20]:
# Loss Bit Joint Prbability of OOK for M = 1
# P_XY = np.array([[0.5, 0],
#                  [0.05, 0.45]])

P_XY = np.array([[1, 0], 
                 [0.1, 0.9]]) * 1/2

In [21]:
M(P_XY)

1.0

In [22]:
print('Loss Bit for M = 1')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Joint Probability P(X, Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

Loss Bit for M = 1
Number of Time Bin 1.0
Probability P(X): [0.5 0.5]
Probability P(Y): [0.55 0.45]
Joint Probability P(X, Y):
[[0.5  0.  ]
 [0.05 0.45]]
Conditional Probability P(X|Y):
[[0.90909091 0.        ]
 [0.09090909 1.        ]]
Conditional Probability P(Y|X):
[[1.  0. ]
 [0.1 0.9]]
Entropy H(X): 1.0 3
Entropy H(Y): 0.9927744539878083 2550791/856452
Joint Entropy H(X,Y): 1.2344977963618322 2580709/696831
Conditional Entropy H(X|Y): 0.2417233425832146 245771/338915
Conditional Entropy H(Y|X): 0.23449779657823633 682250/969803
Mutual Information I(X;Y)): 0.758276657409572
Mutual Information per Photon I(X;Y) / (M/2)): 1.516553314819144


In [23]:
- (0.55 * np.log2(0.55) + 0.45 * np.log2(0.45))

0.9927744539878083

In [24]:
-(0.5 * np.log2(0.5) + 0 + 0.05 * np.log2(0.05) + 0.45 * np.log2(0.45))

1.2344977967946407

In [25]:
# Loss Bit Joint Prbability of OOK for M = 2
P_XY = np.array([[0.25, 0, 0, 0],
                [0.025, 0.225, 0, 0],
                [0.025, 0, 0.225, 0],
                [0.0025, 0.00225, 0.225, 0.2025]])


In [26]:
print('Flip Bit for M = 2')
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Conditional Probability P(X|Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

Flip Bit for M = 2
Number of Time Bin 2.0
Probability P(X): [0.25    0.25    0.25    0.43225]
Probability P(Y): [0.3025  0.22725 0.45    0.2025 ]
Conditional Probability P(X|Y):
[[0.25    0.      0.      0.     ]
 [0.025   0.225   0.      0.     ]
 [0.025   0.      0.225   0.     ]
 [0.0025  0.00225 0.225   0.2025 ]]
Conditional Probability P(X|Y):
[[0.82644628 0.         0.         0.        ]
 [0.08264463 0.99009901 0.         0.        ]
 [0.08264463 0.         0.5        0.        ]
 [0.00826446 0.00990099 0.5        1.        ]]
Conditional Probability P(Y|X):
[[1.         0.         0.         0.        ]
 [0.1        0.9        0.         0.        ]
 [0.1        0.         0.9        0.        ]
 [0.01       0.009      0.9        0.46847889]]
Entropy H(X): 2.0230493561333107 3
Entropy H(Y): 1.9925534756831556 2550791/856452
Joint Entropy H(X,Y): 2.7266600682282776 2580709/696831
Conditional Entropy H(X|Y): 0.7341065934443541 245771/338915
Conditional Entropy H(Y|X): 0.522122487

## Other Calculation

In [27]:
# Example from Textbook Elements of Information Theory Chapter 2
P_XY = np.array([[1/8, 1/16, 1/32, 1/32],
                 [1/16, 1/8, 1/32, 1/32],
                 [1/16, 1/16, 1/16, 1/16],
                 [1/4, 0, 0, 0]])

In [28]:
print('Number of Time Bin', M(P_XY))
print('Probability P(X):', P_X(P_XY))
print('Probability P(Y):', P_Y(P_XY))

print('Conditional Probability P(X|Y):')
print(P_XY)
print('Conditional Probability P(X|Y):')
print(P_X_Y(P_XY, P_Y(P_XY)))
print('Conditional Probability P(Y|X):')
print(P_Y_X(P_XY, P_X(P_XY)))

print('Entropy H(X):', H_X(P_X(P_XY)), fraction_HX)
print('Entropy H(Y):', H_Y(P_Y(P_XY)), fraction_HY)
print('Joint Entropy H(X,Y):', H_XY(P_XY), fraction_HXY)
print('Conditional Entropy H(X|Y):', H_X_Y((P_X_Y(P_XY, P_Y(P_XY)))), fraction_HXbyY)
print('Conditional Entropy H(Y|X):', H_Y_X((P_Y_X(P_XY, P_X(P_XY)))), fraction_HYbyX)

print('Mutual Information I(X;Y)):', MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))))
print('Mutual Information per Photon I(X;Y) / (M/2)):', MIperPhoton(MutualInformation(H_Y(P_Y(P_XY)), H_Y_X((P_Y_X(P_XY, P_X(P_XY))))), M(P_XY)))

Number of Time Bin 2.0
Probability P(X): [0.25 0.25 0.25 0.25]
Probability P(Y): [0.5   0.25  0.125 0.125]
Conditional Probability P(X|Y):
[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]
Conditional Probability P(X|Y):
[[0.25  0.25  0.25  0.25 ]
 [0.125 0.5   0.25  0.25 ]
 [0.125 0.25  0.5   0.5  ]
 [0.5   0.    0.    0.   ]]
Conditional Probability P(Y|X):
[[0.5   0.25  0.125 0.125]
 [0.25  0.5   0.125 0.125]
 [0.25  0.25  0.25  0.25 ]
 [1.    0.    0.    0.   ]]
Entropy H(X): 2.0 3
Entropy H(Y): 1.75 2550791/856452
Joint Entropy H(X,Y): 3.3749999981244967 2580709/696831
Conditional Entropy H(X|Y): 1.6249999994950564 245771/338915
Conditional Entropy H(Y|X): 1.374999999531124 682250/969803
Mutual Information I(X;Y)): 0.37500000046887605
Mutual Information per Photon I(X;Y) / (M/2)): 0.37500000046887605


In [29]:
-(0.5 * np.log2(0.5) + 0.25 * np.log2(0.25) + 0.125 * np.log2(0.125) + 0.125 * np.log2(0.125))

1.75

In [30]:
-(0.25 * np.log2(0.25) + 0.25 * np.log2(0.25) + 0.25 * np.log2(0.25) + 0.25 * np.log2(0.25))

2.0

In [31]:
1/16

0.0625

In [32]:
0.0625 / 0.25

0.25

In [33]:
0.03125 / 0.25

0.125

In [34]:
1/32

0.03125

In [35]:
-(0.125 * np.log2(0.5) + 0.0625 * np.log2(0.25) + 0.03125 * np.log2(0.125) + 0.03125 * np.log2(0.125) + 0.0625 * np.log2(0.25) + 0.125 * np.log2(0.5) +  0.0625* np.log2(0.125) + 0.25  * np.log2(0.25))

1.375

In [36]:
1.75 - 1.375

0.375